### ISSUE TITLE
CODEOWNERS usage? gh-teams-whitelist examples?

### ISSUE THREAD

**Issue by Jaff** [cloudposse/atlantis#25]
How would I make use of GitHub CODEOWNERS file with atlantis? Likewise, how would I implement support for the gh-teams-whitelist settings?

**Comment by aknysh** [comment]
@Jaff 
please take a look at this description https://github.com/cloudposse/atlantis/blob/master/cmd/server.go#L132 for `gh-teams-whitelist`
