### ISSUE TITLE
Support Git Submodules

### ISSUE THREAD

**Issue by osterman** [cloudposse/atlantis#4]
See: https://github.com/runatlantis/atlantis/issues/311
----
## what
* Support git submodules

## why
* It appears that clones are not recursive: https://github.com/runatlantis/atlantis/blob/f057d6d7d9a76c7b8d85c874a10c4f25f7be7465/server/events/working_dir.go#L113
* Support importing terraform root modules without needing `terragrunt`

## use-case
* We're trying to adapt our deployment methodology to work well with Atlantis
* We keep all of our "root" modules in one repo called [`terraform-root-modules`](https://github.com/cloudposse/terraform-root-modules)
* We then import these modules into various stages (aka environments or accounts)
* We have been using [docker multi-stage](https://github.com/cloudposse/testing.cloudposse.co/blob/master/Dockerfile#L37-L47), but that won't play well with atlantis detecting changes, so we're willing to compromise
* We want to use git submodules instead, with the expectation that atlantis would be able to detect changes for autoplans

---

Technically, looks [very easy](https://stackoverflow.com/a/4438292/1237191) to [implement here](https://github.com/runatlantis/atlantis/blob/f057d6d7d9a76c7b8d85c874a10c4f25f7be7465/server/events/working_dir.go#L113) and we'd be happy contribute the capability.

**Comment by aknysh** [comment]
addressed in https://github.com/cloudposse/atlantis/pull/11
